### PR TITLE
Maps!

### PR DESCRIPTION
**Pull request by lily-soetebier**
I've gone ahead and exported all of the maps into the out folder. I am going to start messing with the ditaval stuff now but I figured i'd go ahead and open up the PR so that you know to take a look at it.

Also, because of the images in the concepts and references that I made, I wasn't able to combine the two maps using submaps. I did however get them to work in other places. I also made a note in the readme about this/my idea for possibly combining as submaps when we revise for the plain language editing project.  

Also (pt. 2)  I added a very very short little introduction to the combined map (literally one sentence). Let me know if you think this is needed or not; i'm on the fence about it.

Let me know what you think about organization of files/feel free to go in and change whatever!

### CODE REVIEW

**Comment by lily-soetebier** [comment]
I made the filtered versions but I had issues with the images loading on the filtered versions specifically. They appear on the others, on my end at least so i'm not really sure whats happening there but I think it'll be fine since we just learned how to do the filters

**Comment by lily-soetebier** [comment]
actually nevermind they disappeared on the other versions too idk what's happening there. I'll email dr. lindgren about it

**Comment by lily-soetebier** [comment]
Merging now as discussed via text

**Review by jckinsey01 — COMMENTED** [review]
I like the idea for fixing the maps and images issue for our final. I think it shows our thinking ahead to the final and how we can make changes to the current project for that! I also think the intro sentence is good and should be kept.

**Pull request merged**
